name: Verify app build (for PRs)

on:
    pull_request:
        types: [opened, synchronize, reopened]

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 120
        steps:
            -   name: Pull upstream 🌏
                uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a # v6.0.2
                with:
                    submodules: recursive

            -   name: Set up JDK 🚀
                uses: actions/setup-java@d2bb5a81bf6132351ee9adcc0bba8261a8d34d48 # v5.2.0
                with:
                    distribution: 'temurin'
                    java-version: '21'

            -   name: Setup Gradle 🚀
                uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0
                with:
                    gradle-version: '9.1.0'

            -   name: Setup Android SDK 🚀
                uses: android-actions/setup-android@v4

            -   name: Compile debug app 💻
                run: |
                    chmod a+x gradlew
                    ./gradlew compileDebugKotlin --no-daemon --no-configuration-cache --stacktrace
