name: Check & Test latest commit

on:
    push:
        branches:
            - devel

permissions:
    contents: read

jobs:
    check-and-build:
        runs-on: ubuntu-latest
        timeout-minutes: 120
        steps:
            -   name: Checkout repository 🌏
                uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a # v6.0.2

            -   name: Set up Java enviroment 🔧
                uses: actions/setup-java@d2bb5a81bf6132351ee9adcc0bba8261a8d34d48 # v5.2.0
                with:
                    java-version: '17'
                    distribution: 'temurin'

            -   name: Set up Gradle enviroment 📦
                uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0
                with:
                    gradle-version: '9.1.0'

            -   name: Build release app 🚀
                run: ./gradlew assembleRelease --rerun-tasks
